version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing deps"
      - npm ci
  build:
    commands:
      - echo "Building"
      - npm run build --if-present

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: no
